"""empty message

Revision ID: 578dbac62814
Revises: 
Create Date: 2020-05-06 21:36:41.863851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578dbac62814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access')
    # ### end Alembic commands ###
